### ISSUE TITLE
Module map file WatermelonDB.modulemap not found, Failed to emit precompiled header

### ISSUE THREAD

**Issue by mk1020** [Nozbe/WatermelonDB#1121]
hello. Please help me. I have already tried a lot and nothing helps
![image](https://user-images.githubusercontent.com/59735474/128095466-c34c502d-ff3b-4608-bd26-ad7cde7d4664.png)

**Comment by moisesynfam** [comment]
I'm having the same problem when building the release version on iOS.

**Comment by mk1020** [comment]
> I'm having the same problem when building the release version on iOS.

my problem was solved by rolling back to an older version of the ios folder(from git), something went wrong locally..

**Comment by moisesynfam** [comment]
Can you point out what was wrong?

**Comment by mk1020** [comment]
> Can you point out what was wrong?

I don't think I had a folder with pods. Maybe something else

**Comment by thanhdevapp** [comment]
error on mac mini m1

**Comment by lucas-u13-figueiredo** [comment]
I'm facing the same issue here. I have set the target iOS >=13.0 but still doesn't work.
Not even downgrading to Watermelon @0.21, as used on the example app, it doesn't work

**Comment by lucianolopezz** [comment]
same problem
