### ISSUE TITLE
Bridgeless Mode support (New Architecture) [0.74]

### ISSUE THREAD

**Issue by angelo-hub** [Nozbe/WatermelonDB#1769]
Bridgeless Mode is going to be default in 0.74 can offer some bandwidth to migrate to bridgeless mode as this is a super cool project

**Comment by enahum** [comment]
Have you been able to make it work even with the bridge on 74? On Android there is no longer `getJSIModulePackage` I cannot seem to find a solution to this yet.

**Comment by enahum** [comment]
@radex do you think you can take a look at this to solve the breaking change introduced by RN 74 ?

**Comment by karengharibyan** [comment]
+

**Comment by hawadlu** [comment]
@angelo-hub Any progress on this one?

**Comment by yuyongmao** [comment]
> Have you been able to make it work even with the bridge on 74? On Android there is no longer `getJSIModulePackage` I cannot seem to find a solution to this yet.

@enahum Is there any progress on this issue? I have the same problem.

**Comment by suman379** [comment]
@radex any plan for new arch?

**Comment by LukasMod** [comment]
@radex Can we get an answer in this thread? 
Are there any plans to restore the compatibility of the library with the latest version of react native (current 0.74.3)?

**Comment by radex** [comment]
Yes, sorry for staying quiet about it. Yes, I'm planning to work on this likely in August.

**Comment by 3210jr** [comment]
Hey @radex - I am happy to help with chores and low hanging fruit re new architecture support. Not my area of expertise but if there is a pull request I will contribute

**Comment by lucaswitch** [comment]
> Hey @radex - I am happy to help with chores and low hanging fruit re new architecture support. Not my area of expertise but if there is a pull request I will contribute

I'm happy to help too

**Comment by juliesaia-vendora** [comment]
I got it working on 0.74.5 (with bridge) with this patch, it reverts the deprecation and removes BridgelessCatalystInstance.kt.

It might be possible to do the same with 0.75, but it will be more difficult because there they actually removed the JSIModule stuff. I might try it later though

Be sure to enable building from source on Android (android/settings.gradle):

```gradle
includeBuild('../node_modules/react-native') {
    dependencySubstitution {
        substitute(module("com.facebook.react:react-android")).using(project(":packages:react-native:ReactAndroid"))
        substitute(module("com.facebook.react:react-native")).using(project(":packages:react-native:ReactAndroid"))
        substitute(module("com.facebook.react:hermes-android")).using(project(":packages:react-native:ReactAndroid:hermes-engine"))
        substitute(module("com.facebook.react:hermes-engine")).using(project(":packages:react-native:ReactAndroid:hermes-engine"))
    }
}
```

The patch:

```
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java
index 7258ab9..6df97c6 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManager.java
@@ -55,6 +55,8 @@ import com.facebook.react.bridge.CatalystInstance;
 import com.facebook.react.bridge.CatalystInstanceImpl;
 import com.facebook.react.bridge.JSBundleLoader;
 import com.facebook.react.bridge.JSExceptionHandler;
+import com.facebook.react.bridge.JSIModulePackage;
+import com.facebook.react.bridge.JSIModuleType;
 import com.facebook.react.bridge.JavaJSExecutor;
 import com.facebook.react.bridge.JavaScriptExecutor;
 import com.facebook.react.bridge.JavaScriptExecutorFactory;
@@ -184,6 +186,7 @@ public class ReactInstanceManager {
   private volatile Boolean mHasStartedDestroying = false;
   private final MemoryPressureRouter mMemoryPressureRouter;
   private final @Nullable JSExceptionHandler mJSExceptionHandler;
+    private final @Nullable JSIModulePackage mJSIModulePackage;
   private final @Nullable UIManagerProvider mUIManagerProvider;
   private final @Nullable ReactPackageTurboModuleManagerDelegate.Builder mTMMDelegateBuilder;
   private List<ViewManager> mViewManagers;
@@ -232,6 +235,7 @@ public class ReactInstanceManager {
       @Nullable DevBundleDownloadListener devBundleDownloadListener,
       int minNumShakes,
       int minTimeLeftInFrameForNonBatchedOperationMs,
+      @Nullable JSIModulePackage jsiModulePackage,
       @Nullable UIManagerProvider uIManagerProvider,
       @Nullable Map<String, RequestHandler> customPackagerCommandHandlers,
       @Nullable ReactPackageTurboModuleManagerDelegate.Builder tmmDelegateBuilder,
@@ -292,6 +296,7 @@ public class ReactInstanceManager {
       }
       mPackages.addAll(packages);
     }
+    mJSIModulePackage = jsiModulePackage;
     mUIManagerProvider = uIManagerProvider;
 
     // Instantiate ReactChoreographer in UI thread.
@@ -1399,15 +1404,20 @@ public class ReactInstanceManager {
       }
     }
 
+    if (mJSIModulePackage != null) {
+      catalystInstance.addJSIModules(
+          mJSIModulePackage.getJSIModules(
+              reactContext, catalystInstance.getJavaScriptContextHolder()));
+    }
+
     if (mUIManagerProvider != null) {
       UIManager uiManager = mUIManagerProvider.createUIManager(reactContext);
       if (uiManager != null) {
-        catalystInstance.setFabricUIManager(uiManager);
-
-        // Initialize the UIManager
         uiManager.initialize();
         catalystInstance.setFabricUIManager(uiManager);
       }
+    } else if (ReactFeatureFlags.enableFabricRenderer) {
+    catalystInstance.getJSIModule(JSIModuleType.UIManager);
     }
     if (mBridgeIdleDebugListener != null) {
       catalystInstance.addBridgeIdleDebugListener(mBridgeIdleDebugListener);
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java
index d467ab9..3ae051f 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactInstanceManagerBuilder.java
@@ -20,6 +20,7 @@ import com.facebook.hermes.reactexecutor.HermesExecutorFactory;
 import com.facebook.infer.annotation.Assertions;
 import com.facebook.react.bridge.JSBundleLoader;
 import com.facebook.react.bridge.JSExceptionHandler;
+import com.facebook.react.bridge.JSIModulePackage;
 import com.facebook.react.bridge.JavaScriptExecutorFactory;
 import com.facebook.react.bridge.NotThreadSafeBridgeIdleDebugListener;
 import com.facebook.react.bridge.UIManagerProvider;
@@ -67,6 +68,7 @@ public class ReactInstanceManagerBuilder {
   private @Nullable JavaScriptExecutorFactory mJavaScriptExecutorFactory;
   private int mMinNumShakes = 1;
   private int mMinTimeLeftInFrameForNonBatchedOperationMs = -1;
+  private @Nullable JSIModulePackage mJSIModulesPackage;
   private @Nullable UIManagerProvider mUIManagerProvider;
   private @Nullable Map<String, RequestHandler> mCustomPackagerCommandHandlers;
   private @Nullable ReactPackageTurboModuleManagerDelegate.Builder mTMMDelegateBuilder;
@@ -77,6 +79,12 @@ public class ReactInstanceManagerBuilder {
 
   /* package protected */ ReactInstanceManagerBuilder() {}
 
+  public ReactInstanceManagerBuilder setJSIModulesPackage(
+      @Nullable JSIModulePackage jsiModulePackage) {
+    mJSIModulesPackage = jsiModulePackage;
+    return this;
+  }
+
   /** Factory for desired implementation of JavaScriptExecutor. */
   public ReactInstanceManagerBuilder setJavaScriptExecutorFactory(
       @Nullable JavaScriptExecutorFactory javaScriptExecutorFactory) {
@@ -353,6 +361,7 @@ public class ReactInstanceManagerBuilder {
         mDevBundleDownloadListener,
         mMinNumShakes,
         mMinTimeLeftInFrameForNonBatchedOperationMs,
+        mJSIModulesPackage,
         mUIManagerProvider,
         mCustomPackagerCommandHandlers,
         mTMMDelegateBuilder,
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java
index 6551937..3f1fb6f 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/ReactNativeHost.java
@@ -10,6 +10,7 @@ package com.facebook.react;
 import android.app.Application;
 import androidx.annotation.Nullable;
 import com.facebook.infer.annotation.Assertions;
+import com.facebook.react.bridge.JSIModulePackage;
 import com.facebook.react.bridge.JavaScriptExecutorFactory;
 import com.facebook.react.bridge.ReactMarker;
 import com.facebook.react.bridge.ReactMarkerConstants;
@@ -84,6 +85,7 @@ public abstract class ReactNativeHost {
             .setLazyViewManagersEnabled(getLazyViewManagersEnabled())
             .setRedBoxHandler(getRedBoxHandler())
             .setJavaScriptExecutorFactory(getJavaScriptExecutorFactory())
+            .setJSIModulesPackage(getJSIModulePackage())
             .setUIManagerProvider(getUIManagerProvider())
             .setInitialLifecycleState(LifecycleState.BEFORE_CREATE)
             .setReactPackageTurboModuleManagerDelegateBuilder(
@@ -125,6 +127,10 @@ public abstract class ReactNativeHost {
     return mApplication;
   }
 
+  protected @Nullable JSIModulePackage getJSIModulePackage() {
+    return null;
+  }
+
   protected @Nullable UIManagerProvider getUIManagerProvider() {
     return reactApplicationContext -> null;
   }
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstance.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstance.java
index b2e2d7c..0ee0dd6 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstance.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstance.java
@@ -120,7 +120,7 @@ public interface CatalystInstance
   RuntimeScheduler getRuntimeScheduler();
 
   @Deprecated
-  <T extends JSIModule> void addJSIModules(List<JSIModuleSpec<T>> jsiModules);
+  void addJSIModules(List<JSIModuleSpec> jsiModules);
 
   /**
    * Returns a hybrid object that contains a pointer to a JS CallInvoker, which is used to schedule
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java
index f86dffb..67e5e35 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/CatalystInstanceImpl.java
@@ -537,8 +537,7 @@ public class CatalystInstanceImpl implements CatalystInstance {
   public native RuntimeScheduler getRuntimeScheduler();
 
   @Override
-  @Deprecated
-  public <T extends JSIModule> void addJSIModules(List<JSIModuleSpec<T>> jsiModules) {
+  public void addJSIModules(List<JSIModuleSpec> jsiModules) {
     mJSIModuleRegistry.registerModules(jsiModules);
   }
   
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/JSIModuleRegistry.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/JSIModuleRegistry.java
index 90d5cde..e81b361 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/JSIModuleRegistry.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/bridge/JSIModuleRegistry.java
@@ -26,8 +26,8 @@ class JSIModuleRegistry {
     return Assertions.assertNotNull(jsiModuleHolder.getJSIModule());
   }
 
-  public <T extends JSIModule> void registerModules(List<JSIModuleSpec<T>> jsiModules) {
-    for (JSIModuleSpec<T> spec : jsiModules) {
+  public void registerModules(List<JSIModuleSpec> jsiModules) {
+    for (JSIModuleSpec spec : jsiModules) {
       mModules.put(spec.getJSIModuleType(), new JSIModuleHolder(spec));
     }
   }
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt
deleted file mode 100644
index 03a18c6..0000000
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessCatalystInstance.kt
+++ /dev/null
@@ -1,194 +0,0 @@
-/*
- * Copyright (c) Meta Platforms, Inc. and affiliates.
- *
- * This source code is licensed under the MIT license found in the
- * LICENSE file in the root directory of this source tree.
- */
-
-package com.facebook.react.runtime
-
-import android.content.res.AssetManager
-import com.facebook.proguard.annotations.DoNotStrip
-import com.facebook.react.bridge.CatalystInstance
-import com.facebook.react.bridge.JSIModule
-import com.facebook.react.bridge.JSIModuleSpec
-import com.facebook.react.bridge.JSIModuleType
-import com.facebook.react.bridge.JavaScriptContextHolder
-import com.facebook.react.bridge.JavaScriptModule
-import com.facebook.react.bridge.NativeArray
-import com.facebook.react.bridge.NativeArrayInterface
-import com.facebook.react.bridge.NativeModule
-import com.facebook.react.bridge.NativeModuleRegistry
-import com.facebook.react.bridge.NotThreadSafeBridgeIdleDebugListener
-import com.facebook.react.bridge.RuntimeExecutor
-import com.facebook.react.bridge.RuntimeScheduler
-import com.facebook.react.bridge.UIManager
-import com.facebook.react.bridge.queue.ReactQueueConfiguration
-import com.facebook.react.common.annotations.DeprecatedInNewArchitecture
-import com.facebook.react.common.annotations.VisibleForTesting
-import com.facebook.react.internal.turbomodule.core.interfaces.TurboModuleRegistry
-import com.facebook.react.turbomodule.core.interfaces.CallInvokerHolder
-import com.facebook.react.turbomodule.core.interfaces.NativeMethodCallInvokerHolder
-
-@DoNotStrip
-@DeprecatedInNewArchitecture
-public class BridgelessCatalystInstance(private val reactHost: ReactHostImpl) : CatalystInstance {
-
-  override fun handleMemoryPressure(level: Int) {
-    throw UnsupportedOperationException("Unimplemented method 'handleMemoryPressure'")
-  }
-
-  override fun loadScriptFromAssets(
-      assetManager: AssetManager,
-      assetURL: String,
-      loadSynchronously: Boolean
-  ) {
-    throw UnsupportedOperationException("Unimplemented method 'loadScriptFromAssets'")
-  }
-
-  override fun loadScriptFromFile(fileName: String, sourceURL: String, loadSynchronously: Boolean) {
-    throw UnsupportedOperationException("Unimplemented method 'loadScriptFromFile'")
-  }
-
-  override fun loadSplitBundleFromFile(fileName: String, sourceURL: String) {
-    throw UnsupportedOperationException("Unimplemented method 'loadSplitBundleFromFile'")
-  }
-
-  override fun setSourceURLs(deviceURL: String, remoteURL: String) {
-    throw UnsupportedOperationException("Unimplemented method 'setSourceURLs'")
-  }
-
-  override fun runJSBundle() {
-    throw UnsupportedOperationException("Unimplemented method 'runJSBundle'")
-  }
-
-  override fun hasRunJSBundle(): Boolean {
-    throw UnsupportedOperationException("Unimplemented method 'hasRunJSBundle'")
-  }
-
-  override fun getSourceURL(): String? {
-    throw UnsupportedOperationException("Unimplemented method 'getSourceURL'")
-  }
-
-  @DoNotStrip
-  override fun invokeCallback(callbackID: Int, arguments: NativeArrayInterface) {
-    throw UnsupportedOperationException("Unimplemented method 'invokeCallback'")
-  }
-
-  override fun callFunction(module: String, method: String, arguments: NativeArray) {
-    throw UnsupportedOperationException("Unimplemented method 'callFunction'")
-  }
-
-  override fun destroy() {
-    throw UnsupportedOperationException("Unimplemented method 'destroy'")
-  }
-
-  override fun isDestroyed(): Boolean {
-    throw UnsupportedOperationException("Unimplemented method 'isDestroyed'")
-  }
-
-  @VisibleForTesting
-  override fun initialize() {
-    throw UnsupportedOperationException("Unimplemented method 'initialize'")
-  }
-
-  override fun getReactQueueConfiguration(): ReactQueueConfiguration =
-      reactHost.reactQueueConfiguration!!
-
-  override fun <T : JavaScriptModule> getJSModule(jsInterface: Class<T>): T =
-      reactHost.currentReactContext?.getJSModule(jsInterface)!!
-
-  override fun <T : NativeModule> hasNativeModule(nativeModuleInterface: Class<T>): Boolean =
-      reactHost.hasNativeModule(nativeModuleInterface)
-
-  override fun <T : NativeModule> getNativeModule(nativeModuleInterface: Class<T>): T? =
-      reactHost.getNativeModule(nativeModuleInterface)
-
-  override fun getNativeModule(moduleName: String): NativeModule? =
-      reactHost.getNativeModule(moduleName)
-
-  @Deprecated(
-      message =
-          "getJSIModule(JSIModuleType moduleType) is deprecated and will be deleted in the future. Please use ReactInstanceEventListener to subscribe for react instance events instead.")
-  override fun getJSIModule(moduleType: JSIModuleType): JSIModule {
-    throw UnsupportedOperationException("Unimplemented method 'getJSIModule'")
-  }
-
-  override fun getNativeModules(): Collection<NativeModule> = reactHost.getNativeModules()
-
-  override fun extendNativeModules(modules: NativeModuleRegistry) {
-    throw UnsupportedOperationException("Unimplemented method 'extendNativeModules'")
-  }
-
-  override fun addBridgeIdleDebugListener(listener: NotThreadSafeBridgeIdleDebugListener) {
-    throw UnsupportedOperationException("Unimplemented method 'addBridgeIdleDebugListener'")
-  }
-
-  override fun removeBridgeIdleDebugListener(listener: NotThreadSafeBridgeIdleDebugListener) {
-    throw UnsupportedOperationException("Unimplemented method 'removeBridgeIdleDebugListener'")
-  }
-
-  override fun registerSegment(segmentId: Int, path: String) {
-    throw UnsupportedOperationException("Unimplemented method 'registerSegment'")
-  }
-
-  @VisibleForTesting
-  override fun setGlobalVariable(propName: String, jsonValue: String) {
-    throw UnsupportedOperationException("Unimplemented method 'setGlobalVariable'")
-  }
-
-  @Deprecated(message = "This API is unsupported in the New Architecture.")
-  override fun getJavaScriptContextHolder(): JavaScriptContextHolder? {
-    return reactHost.getJavaScriptContextHolder()
-  }
-
-  override fun getRuntimeExecutor(): RuntimeExecutor? {
-    return reactHost.getRuntimeExecutor()
-  }
-
-  override fun getRuntimeScheduler(): RuntimeScheduler {
-    throw UnsupportedOperationException("Unimplemented method 'getRuntimeScheduler'")
-  }
-
-  @Deprecated(message = "This API is unsupported in the New Architecture.")
-  override fun <T : JSIModule> addJSIModules(jsiModules: List<JSIModuleSpec<T>>) {
-    throw UnsupportedOperationException("Unimplemented method 'addJSIModules'")
-  }
-
-  override fun getJSCallInvokerHolder(): CallInvokerHolder? {
-    return reactHost.getJSCallInvokerHolder()
-  }
-
-  override fun getNativeMethodCallInvokerHolder(): NativeMethodCallInvokerHolder {
-    throw UnsupportedOperationException("Unimplemented method 'getNativeMethodCallInvokerHolder'")
-  }
-
-  @Deprecated(
-      message =
-          "setTurboModuleManager(JSIModule getter) is deprecated and will be deleted in the future. Please use setTurboModuleRegistry(TurboModuleRegistry turboModuleRegistry) instead.",
-      replaceWith = ReplaceWith("setTurboModuleRegistry(turboModuleRegistry)"))
-  override fun setTurboModuleManager(getter: JSIModule) {
-    throw UnsupportedOperationException("Unimplemented method 'setTurboModuleManager'")
-  }
-
-  @DeprecatedInNewArchitecture(
-      message =
-          "This method will be deprecated later as part of Stable APIs with bridge removal and not encouraged usage.")
-  override fun setTurboModuleRegistry(turboModuleRegistry: TurboModuleRegistry) {
-    throw UnsupportedOperationException("Unimplemented method 'setTurboModuleRegistry'")
-  }
-
-  @DeprecatedInNewArchitecture(
-      message =
-          "This method will be deprecated later as part of Stable APIs with bridge removal and not encouraged usage.")
-  override fun setFabricUIManager(fabricUIManager: UIManager) {
-    throw UnsupportedOperationException("Unimplemented method 'setFabricUIManager'")
-  }
-
-  @DeprecatedInNewArchitecture(
-      message =
-          "This method will be deprecated later as part of Stable APIs with bridge removal and not encouraged usage.")
-  override fun getFabricUIManager(): UIManager {
-    throw UnsupportedOperationException("Unimplemented method 'getFabricUIManager'")
-  }
-}
diff --git a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessReactContext.java b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessReactContext.java
index d1cdaa9..24cc18a 100644
--- a/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessReactContext.java
+++ b/node_modules/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessReactContext.java
@@ -81,14 +81,6 @@ class BridgelessReactContext extends ReactApplicationContext implements EventDis
     return mReactHost.getUIManager();
   }
 
-  @Override
-  public CatalystInstance getCatalystInstance() {
-    Log.w(
-        TAG,
-        "[WARNING] Bridgeless doesn't support CatalystInstance. Accessing an API that's not part of the new architecture is not encouraged usage.");
-    return new BridgelessCatalystInstance(mReactHost);
-  }
-
   @Override
   public boolean hasActiveReactInstance() {
     return mReactHost.isInstanceInitialized();

```

Really frustrating that the RN changelog mentions that this was unused in open source, idk how they missed this huge repo

**Comment by LukasMod** [comment]
@radex Could you update how you see the progress of this work?

We're trying to get the app ready for the new architecture as of version 0.76 and are looking for issues among the key libraries. Without watermelonDB it probably won't be possible, so any information about the progress/plans would be super valuable. Maybe someone advanced from the community would be able to help solve some problems.

**Comment by swapnil001** [comment]
Hi, Any update on solution for this?

**Comment by prathameshmm02** [comment]
WatermelonDB JSI module can be registered like this in React Native 0.74+:

MainApplication.kt
```kt
import others....
import com.facebook.react.ReactInstanceManager
import com.nozbe.watermelondb.jsi.JSIInstaller
import com.facebook.react.bridge.ReactContext
import com.facebook.react.bridge.UiThreadUtil

class MainApplication : Application(), ReactApplication {
....
    private var listenerAdded = false
    override fun onCreate() {
        super.onCreate()
        ....
        registerJSIModules()
    }

    private fun runOnJSQueueThread(action: () -> Unit) {
        reactNativeHost.reactInstanceManager.currentReactContext?.runOnJSQueueThread {
            action()
        } ?: UiThreadUtil.runOnUiThread {
            reactNativeHost.reactInstanceManager.currentReactContext?.runOnJSQueueThread {
                action()
            }
        }
    }

    @Suppress("DEPRECATION")
    private fun registerJSIModules() {
        val reactInstanceManager = reactNativeHost.reactInstanceManager

        if (!listenerAdded) {
            listenerAdded = true
            reactInstanceManager.addReactInstanceEventListener(object : ReactInstanceManager.ReactInstanceEventListener {
                override fun onReactContextInitialized(context: ReactContext) {
                    runOnJSQueueThread {
                        registerWatermelonJSI(context)
                    }
                }
            })
        }
    }

    private fun registerWatermelonJSI(context: ReactContext) {
        val holder = context.javaScriptContextHolder?.get()
        if (holder != null) {
            JSIInstaller.install(context, holder)
        }
    }
}
```

A patch is also required to make JSIInstaller class and methods public.

```diff
diff --git a/native/android-jsi/src/main/java/com/nozbe/watermelondb/jsi/JSIInstaller.java b/native/android-jsi/src/main/java/com/nozbe/watermelondb/jsi/JSIInstaller.java
index 055cede2f20cd6a75ffb79d156e35396c1438c91..fb7ca33847aa9ad1349b10b35d4e27575e843479 100755
--- a/native/android-jsi/src/main/java/com/nozbe/watermelondb/jsi/JSIInstaller.java
+++ b/native/android-jsi/src/main/java/com/nozbe/watermelondb/jsi/JSIInstaller.java
@@ -1,8 +1,8 @@
 package com.nozbe.watermelondb.jsi;
 
 import android.content.Context;
-class JSIInstaller {
-    static void install(Context context, long javaScriptContextHolder) {
+public class JSIInstaller {
+    public static void install(Context context, long javaScriptContextHolder) {
         JSIInstaller.context = context;
         new JSIInstaller().installBinding(javaScriptContextHolder);
 
```


Reference: https://github.com/mattermost/mattermost-mobile/blob/main/android/app/src/main/java/com/mattermost/rnbeta/MainApplication.kt

Didn't get the time to test this, but probably should work?

**Comment by enahum** [comment]
The above works, but I have not tested it with 0.75.x

**Comment by ishan-chhabra** [comment]
Hi @prathameshmm02 @enahum!

I did try the workaround above but it did not work for me.
I still get this error while syncing in turbo.

```
Error while syncing [Error: provideSyncJson unavailable. Use JSI mode to enable.]
```

MainApplication.kt
```kotlin
package something.something

import android.app.Application
import android.content.res.Configuration
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.soloader.SoLoader
import java.util.Arrays
import com.facebook.react.bridge.JSIModulePackage
import com.facebook.react.bridge.JSIModule
import com.facebook.react.bridge.JSIModuleSpec
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.JavaScriptContextHolder
import expo.modules.ApplicationLifecycleDispatcher
import expo.modules.ReactNativeHostWrapper
import com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage
import com.facebook.react.ReactInstanceManager
import com.nozbe.watermelondb.jsi.JSIInstaller
import com.facebook.react.bridge.ReactContext
import com.facebook.react.bridge.UiThreadUtil

class MainApplication : Application(), ReactApplication {

  private var listenerAdded = false
  override val reactNativeHost: ReactNativeHost =
      ReactNativeHostWrapper(this, object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
            }

        override fun getJSMainModuleName(): String = "index"

        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      })

  override val reactHost: ReactHost
    get() = ReactNativeHostWrapper.createReactHost(applicationContext, reactNativeHost)

    override fun onCreate() {
    super.onCreate()
    
    SoLoader.init(this, false)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      load()
    }
    ApplicationLifecycleDispatcher.onApplicationCreate(this)
    registerJSIModules()
  }

    private fun runOnJSQueueThread(action: () -> Unit) {
        reactNativeHost.reactInstanceManager.currentReactContext?.runOnJSQueueThread {
            action()
        } ?: UiThreadUtil.runOnUiThread {
            reactNativeHost.reactInstanceManager.currentReactContext?.runOnJSQueueThread {
                action()
            }
        }
    }

  @Suppress("DEPRECATION")
  private fun registerJSIModules() {
    val reactInstanceManager = reactNativeHost.reactInstanceManager

    if (!listenerAdded) {
        listenerAdded = true
        reactInstanceManager.addReactInstanceEventListener(object : ReactInstanceManager.ReactInstanceEventListener {
          override fun onReactContextInitialized(context: ReactContext) {
              runOnJSQueueThread {
                registerWatermelonJSI(context)
              }
            }
          })
        }
    }

  private fun registerWatermelonJSI(context: ReactContext) {
      val holder = context.javaScriptContextHolder?.get()
      if (holder != null) {
          JSIInstaller.install(context, holder)
      }
  }

  override fun onConfigurationChanged(newConfig: Configuration) {
    super.onConfigurationChanged(newConfig)
    ApplicationLifecycleDispatcher.onConfigurationChanged(this, newConfig)
  }
}
```

I also patched WatermelonDB as follows:

@nozbe+watermelondb+0.27.1.patch
```diff
diff --git a/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/java/com/nozbe/watermelondb/jsi/JSIInstaller.java b/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/java/com/nozbe/watermelondb/jsi/JSIInstaller.java
index 055cede..fb7ca33 100755
--- a/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/java/com/nozbe/watermelondb/jsi/JSIInstaller.java
+++ b/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/java/com/nozbe/watermelondb/jsi/JSIInstaller.java
@@ -1,8 +1,8 @@
 package com.nozbe.watermelondb.jsi;
 
 import android.content.Context;
-class JSIInstaller {
-    static void install(Context context, long javaScriptContextHolder) {
+public class JSIInstaller {
+    public static void install(Context context, long javaScriptContextHolder) {
         JSIInstaller.context = context;
         new JSIInstaller().installBinding(javaScriptContextHolder);
```

I have also verified that all the changes stated in JSI setup on https://watermelondb.dev/docs/Installation#android-react-native are applied.

Any help will be greatly appreciated. Thank youu! :)

**Comment by prathameshmm02** [comment]
@ishan-chhabra Do you have JSI enabled in your adapter? 
```ts
const adapter = new SQLiteAdapter({
  schema,
  migrations,
  jsi: true,
  })
```

**Comment by arun-saleth** [comment]
@prathameshmm02  JSI SQLiteAdapter not available… falling back to asynchronous operation. This will happen if you're using remote debugger, and may happen if you forgot to recompile native app after WatermelonDB update

**Comment by prathameshmm02** [comment]
Have you followed JSI installation docs in Android section given [here](https://watermelondb.dev/docs/Installation)? After doing that, recompile your app and it should work fine.

**Comment by arun-saleth** [comment]
@prathameshmm02 

package com.nozbe.watermelondb.jsi;

import android.content.Context;
public class JSIInstaller {
   public static void install(Context context, long javaScriptContextHolder) {
        JSIInstaller.context = context;
        new JSIInstaller().installBinding(javaScriptContextHolder);

        // call methods we're going to need from JNI - if we don't, Proguard/R8 will strip it from
        // release binaries. We could use @Keep or configure Proguard to keep it but that would be
        // error prone for lib users
        _resolveDatabasePath("");
    }

    // Helper method called from C++
    static String _resolveDatabasePath(String dbName) {
        // On some systems there is some kind of lock on `/databases` folder ¯\_(ツ)_/¯
        return context.getDatabasePath(dbName + ".db").getPath().replace("/databases", "");
    }

    private native void installBinding(long javaScriptContextHolder);

    static native void provideSyncJson(int id, byte[] json);

    static native void destroy();

    private static Context context;

    static {
        System.loadLibrary("watermelondb-jsi");
    }
}

**Comment by arun-saleth** [comment]
How to implement this.it show override nothing error

`// ...
import com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage; // ⬅️ This!
import com.facebook.react.bridge.JSIModulePackage; // ⬅️ This!
// ...
private final ReactNativeHost mReactNativeHost =
   new ReactNativeHost(this) {
     // ...

     @Override
     protected JSIModulePackage getJSIModulePackage() {
       return new WatermelonDBJSIPackage(); // ⬅️ This!
     }
   }
`

**Comment by aleksey-mukho** [comment]
Looks like this library is no longer supported. Very sad news.

**Comment by angelo-hub** [comment]
yeah if you want to continue using SQL on react-native recommend the `expo/sqlite` next gen library

**Comment by HieronymusLex** [comment]
> Has anyone thought about migrating to a new library? Currently eyeing https://github.com/OP-Engineering/op-sqlite however not sure how stable it is and also it will be a pain to have to do migration...

Have you had any thoughts on a strategy for migrating to something like expo-sqlite could be done for existing apps?

**Comment by HieronymusLex** [comment]
> I would very much rather not migrate. It is always a risk, but if I am forced to do it I would suggest migrating it by initially migrating only 1 table with a fallback value provider function. Kind of like maintaining a replica and you should write to both databases, then once you are sure it works switch to it completely. 

Agreed I would rather not but fear it might be required. In any case, moving that discussion to #1861

**Comment by radex** [comment]
Hi everyone,

Apologies for the long time with no updates. Unfortunately, I have not been able to find enough time recently to work on WatermelonDB. I'm very sorry about promising/suggesting that this would be done in August given that I was not able to deliver on that promise.

I have a new pre-release version: v0.28.0-1 - that should fix building of the project on Android/JSI. Note that you need to move `WatermelonDBJSIPackage()` to `getPackages()` in your MainApplication.kt.

Feedback on the pre-release would be appreciated!

**Comment by LukasMod** [comment]
I can confirm v0.28.0-1 is working in our product with react-native: 0.76.3 old arch with db jsi enabled. At first glance, it looks like it's working properly 👍

**Comment by CodeWithBlaze** [comment]
will this also work on the 0.76+ new arch and jsi enabled ? because i am getting strange errors like this 
` Caused by: java.lang.NullPointerException
                                                                                                    	at com.facebook.react.runtime.BridgelessCatalystInstance.getReactQueueConfiguration(BridgelessCatalystInstance.kt:116)
                                                                                                    	at com.nozbe.watermelondb.WMDatabaseBridge.invalidate(WMDatabaseBridge.java:251)
                                                                                                    	at com.facebook.react.internal.turbomodule.core.TurboModuleManager.invalidate(TurboModuleManager.java:417)`
                                                                                                    	
when i reload the app

**Comment by MatheusHCP** [comment]
In Expo SDK 52, React Native 0.76, New Arch Enable and JSI Disable on Android, i receiving this message in android:

Diagnostic error: NativeModules.WMDatabaseBridge is not defined! This means that you haven't properly linked WatermelonDB native module. Refer to docs for instructions about installation (and the changelog if this happened after an upgrade).

I implemented manual link described in Installation.MDX, I try to update my application to the new arch.

**Comment by caiopratali** [comment]
> In Expo SDK 52, React Native 0.76, New Arch Enable and JSI Disable on Android, i receiving this message in android:
> 
> Diagnostic error: NativeModules.WMDatabaseBridge is not defined! This means that you haven't properly linked WatermelonDB native module. Refer to docs for instructions about installation (and the changelog if this happened after an upgrade).
> 
> I implemented manual link described in Installation.MDX, I try to update my application to the new arch.

Did it work with the manual link?

**Comment by caiopratali** [comment]
> > > In Expo SDK 52, React Native 0.76, New Arch Enable and JSI Disable on Android, i receiving this message in android:
> > > Diagnostic error: NativeModules.WMDatabaseBridge is not defined! This means that you haven't properly linked WatermelonDB native module. Refer to docs for instructions about installation (and the changelog if this happened after an upgrade).
> > > I implemented manual link described in Installation.MDX, I try to update my application to the new arch.
> > 
> > 
> > Did it work with the manual link?
> > ![image](https://private-user-images.githubusercontent.com/10279814/391966691-b41c070d-a814-40ad-8f97-cd7d419f5a43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMjk3OTUsIm5iZiI6MTczMzIyOTQ5NSwicGF0aCI6Ii8xMDI3OTgxNC8zOTE5NjY2OTEtYjQxYzA3MGQtYTgxNC00MGFkLThmOTctY2Q3ZDQxOWY1YTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDEyMzgxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4OTVlZTI2MzhlMjQ5MjhkZDFhNWQ2NTc3OTU2ZjBmODdkMjMzMjg0MDczYTI3Mzg3YzZiZjgzYjhiZTJkOTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pekkM8z9Wuy3ZhzbGtgwzcb_Qg2gZQxZa1ZXoCiZ4uQ)
> 
> No.

I had managed to use it without newArch, for the link on Android I installed @react-native-community/cli and added EXPO_USE_COMMUNITY_AUTOLINKING=1 as suggested in the expo documentation, but my app randomly stopped working. 

Expo Autolinking: https://docs.expo.dev/modules/autolinking/#opting-out-of-expo-autolinking

**Comment by juliesaia-vendora** [comment]
anyone gotten this to link properly on android yet? still getting `Proprety 'WMDatabaseJSIBridge' doesn't exist` with this MainApplication.kt:

```
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage());
              add(WatermelonDBJSIPackage())
            }
```

**Comment by saurabhspinny** [comment]
> will this also work on the 0.76+ new arch and jsi enabled ? because i am getting strange errors like this ` Caused by: java.lang.NullPointerException at com.facebook.react.runtime.BridgelessCatalystInstance.getReactQueueConfiguration(BridgelessCatalystInstance.kt:116) at com.nozbe.watermelondb.WMDatabaseBridge.invalidate(WMDatabaseBridge.java:251) at com.facebook.react.internal.turbomodule.core.TurboModuleManager.invalidate(TurboModuleManager.java:417)`
> 
> when i reload the app
> 
> @radex can you confirm this please. Using pre-release version 0.28.1

@radex I am also getting the same error. Could you please provide a fix for this?

**Comment by KrisLau** [comment]
@radex any rough idea on when the new arch will be supported? What is left to be done that maybe anyone here could help with?

**Comment by clmoreno** [comment]
Is anyone having issues with the pre-release ? i have been using it on a group of beta testers for a week now and is working fine.

**Comment by saurabhsaneja** [comment]
@clmoreno having issue with react Native cli

**Comment by limbo56** [comment]
@CodeWithBlaze
@saurabhspinny

### Fix for Bridgeless Architecture Error on App Reload

If you're running into the following error with the new architecture when reloading your app:
```
Caused by: java.lang.NullPointerException 
  at com.facebook.react.runtime.BridgelessCatalystInstance.getReactQueueConfiguration(BridgelessCatalystInstance.kt:116)
  at com.nozbe.watermelondb.WMDatabaseBridge.invalidate(WMDatabaseBridge.java:251) 
  at com.facebook.react.internal.turbomodule.core.TurboModuleManager.invalidate(TurboModuleManager.java:417)
```

This issue arises because the new **Bridgeless architecture** does not support `CatalystInstance`, as mentioned in the [React Native source code](https://github.com/facebook/react-native/blob/980458c061580bbc004bf1ddc17f567fc51aaab8/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessReactContext.java#L86-L89).

### Solution
The fix involves replacing `getCatalystInstance().getReactQueueConfiguration().getJSQueueThread()` with `getJSMessageQueueThread()` to maintain compatibility with the Bridgeless architecture:
```patch
diff --git a/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java b/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
index 117b2bc1f75217c685bc9cfa76b4e55b22e015dc..a678d5d1715d633c4518a04b11fd1198c53157e9 100644
--- a/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
+++ b/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
@@ -248,7 +248,7 @@ public class WMDatabaseBridge extends ReactContextBaseJavaModule {
     public void invalidate() {
         // NOTE: See Database::install() for explanation
         super.invalidate();
-        reactContext.getCatalystInstance().getReactQueueConfiguration().getJSQueueThread().runOnQueue(() -> {
+        reactContext.getJSMessageQueueThread().runOnQueue(() -> {
             try {
                 Class<?> clazz = Class.forName("com.nozbe.watermelondb.jsi.WatermelonJSI");
                 Method method = clazz.getDeclaredMethod("onCatalystInstanceDestroy");

```

I’ve submitted [a pull request with this fix](https://github.com/Nozbe/WatermelonDB/pull/1875) and would appreciate it being merged. Hope this helps!

**Comment by dppo** [comment]
> @CodeWithBlaze @saurabhspinny
> 
> ### Fix for Bridgeless Architecture Error on App Reload
> If you're running into the following error with the new architecture when reloading your app:
> 
> ```
> Caused by: java.lang.NullPointerException 
>   at com.facebook.react.runtime.BridgelessCatalystInstance.getReactQueueConfiguration(BridgelessCatalystInstance.kt:116)
>   at com.nozbe.watermelondb.WMDatabaseBridge.invalidate(WMDatabaseBridge.java:251) 
>   at com.facebook.react.internal.turbomodule.core.TurboModuleManager.invalidate(TurboModuleManager.java:417)
> ```
> 
> This issue arises because the new **Bridgeless architecture** does not support `CatalystInstance`, as mentioned in the [React Native source code](https://github.com/facebook/react-native/blob/980458c061580bbc004bf1ddc17f567fc51aaab8/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessReactContext.java#L86-L89).
> 
> ### Solution
> The fix involves replacing `getCatalystInstance().getReactQueueConfiguration().getJSQueueThread()` with `getJSMessageQueueThread()` to maintain compatibility with the Bridgeless architecture:
> 
> ```diff
> diff --git a/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java b/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
> index 117b2bc1f75217c685bc9cfa76b4e55b22e015dc..a678d5d1715d633c4518a04b11fd1198c53157e9 100644
> --- a/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
> +++ b/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
> @@ -248,7 +248,7 @@ public class WMDatabaseBridge extends ReactContextBaseJavaModule {
>      public void invalidate() {
>          // NOTE: See Database::install() for explanation
>          super.invalidate();
> -        reactContext.getCatalystInstance().getReactQueueConfiguration().getJSQueueThread().runOnQueue(() -> {
> +        reactContext.getJSMessageQueueThread().runOnQueue(() -> {
>              try {
>                  Class<?> clazz = Class.forName("com.nozbe.watermelondb.jsi.WatermelonJSI");
>                  Method method = clazz.getDeclaredMethod("onCatalystInstanceDestroy");
> ```
> 
> I’ve submitted [a pull request with this fix](https://github.com/Nozbe/WatermelonDB/pull/1875) and would appreciate it being merged. Hope this helps!

Is it cleaner to use `reactContext.runOnJSQueueThread`?

**Comment by limbo56** [comment]
@dppo You're right, and `reactContext.runOnJSQueueThread()` ensures the JS MessageQueueThread isn't null. I've updated my comment and PR with this change and credited you. Thanks for the suggestion!

**Comment by saurabhsaneja** [comment]
@limbo56 will this change also work with react native 0.76.0 and watermelon db version 0.28.1-1?

**Comment by limbo56** [comment]
@saurabhsaneja Yes, I'm running React Native 0.76.6 and WatermelonDB 0.28.0-1, and that change resolved the issue.

**Comment by Rohit3523** [comment]
> @saurabhsaneja Yes, I'm running React Native 0.76.6 and WatermelonDB 0.28.0-1, and that change resolved the issue.

Are you using it with newArch enabled?

**Comment by limbo56** [comment]
@Rohit3523 Yes

**Comment by saurabhspinny** [comment]
@limbo56 are you importing com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage in MainApplication.kt file and adding it like this: packages.add(WatermelonDBJSIPackage())

or are you importing com.nozbe.watermelondb.jsi.JSIInstaller and registering it using registerWatermelonJSI method like @prathameshmm02 mentioned

when i am importing com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage like this, i am getting NativeModules.WMDatabaseBridge is not defined error

also, are you linking watermelon db manually or linking it using JSI installation (Optional, recommended) like mentioned in documention link below:
https://watermelondb.dev/docs/Installation

**Comment by limbo56** [comment]
@saurabhspinny Apologies for getting back so late. I am installing WatermelonDB with JSI. Here's what I did:

* I imported `com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage` in `MainApplication.kt`.
* Then, I registered it using `packages.add(WatermelonDBJSIPackage())` inside the `getPackages()` method of `ReactNativeHost`.

If you're running into the `NativeModules.WMDatabaseBridge is not defined error`, there might be an issue with your setup. Double-check that you followed the JSI Installation steps in the documentation.

For reference, I’m using a bare workflow Expo project with SDK 52.

**Comment by saurabhsaneja** [comment]
@limbo56 Hey, thanks for getting back. I was able to make it work with manual linking and changing just one line of watermelon db like you mentioned. Maybe for react native cli project 0.76 version, jsi installation has issues

**Comment by arun-saleth** [comment]
```
import android.app.Application
import com.facebook.react.PackageList
import com.facebook.react.ReactApplication
import com.facebook.react.ReactHost
import com.facebook.react.ReactNativeHost
import com.facebook.react.ReactPackage
import com.facebook.react.defaults.DefaultNewArchitectureEntryPoint.load
import com.facebook.react.defaults.DefaultReactHost.getDefaultReactHost
import com.facebook.react.defaults.DefaultReactNativeHost
import com.facebook.soloader.SoLoader
import android.content.BroadcastReceiver
import android.content.Context
import android.content.Intent
import android.content.IntentFilter
import android.os.Build
import org.jetbrains.annotations.Nullable
import com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage

class MainApplication : Application(), ReactApplication {

  override val reactNativeHost: ReactNativeHost =
      object : DefaultReactNativeHost(this) {
         override fun getPackages(): List<ReactPackage> =
            listOf(WatermelonDBJSIPackage())

        override fun getJSMainModuleName(): String = "index"

        override fun getUseDeveloperSupport(): Boolean = BuildConfig.DEBUG

        override val isNewArchEnabled: Boolean = BuildConfig.IS_NEW_ARCHITECTURE_ENABLED
        override val isHermesEnabled: Boolean = BuildConfig.IS_HERMES_ENABLED
      }

  override val reactHost: ReactHost
    get() = getDefaultReactHost(applicationContext, reactNativeHost)

    override fun registerReceiver(@Nullable receiver: BroadcastReceiver?, filter: IntentFilter): Intent? {
      return if (Build.VERSION.SDK_INT >= 34 && applicationInfo.targetSdkVersion >= 34) {
          super.registerReceiver(receiver, filter, Context.RECEIVER_EXPORTED)
      } else {
          super.registerReceiver(receiver, filter)
      }
  }

  override fun onCreate() {
    super.onCreate()
    SoLoader.init(this, false)
    if (BuildConfig.IS_NEW_ARCHITECTURE_ENABLED) {
      // If you opted-in for the New Architecture, we load the native entry point for this app.
      load()
    }
  }
}
```
After adding WatermelonDBJSIPackage facing this error and app is not running 0.74.3 and newArchEnabled=false mode

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNBootSplash' could not be found. Verify that a module by this name is registered in the native binary.Bridgeless mode: false. TurboModule interop: false. Modules loaded: {"NativeModules":["PlatformConstants","LogBox","Timing"],"TurboModules":[],"NotFound":["NativePerformanceCxx","NativePerformanceObserverCxx","AppState","RNBootSplash"]}, js engine: hermes

**Comment by saurabhsaneja** [comment]
@arun-saleth i could make it work by not using jsi installation

**Comment by arun-saleth** [comment]
@saurabhsaneja  Can you share example code

**Comment by saurabhspinny** [comment]
@arun-saleth just make changes to WMDatabaseBridge.java file like limbo56 said, and link manually as mentioned in documention https://watermelondb.dev/docs/Installation

it will work with new arch enabled.. i make these changes and it works

within MainApplication.kt file,
import com.nozbe.watermelondb.WatermelonDBPackage

later add it within getPackages function
packages.add(WatermelonDBPackage())

**Comment by rohankm** [comment]
Will JSI work?

**Comment by 3210jr** [comment]
> Will JSI work?
> 

Use 0.28-2 release. I think it's on the latest tag release. Works for me with new architecture. I think it's in Beta so do serious testing before publishing your app updates.

**Comment by rohankm** [comment]
> [@arun-saleth](https://github.com/arun-saleth) just make changes to WMDatabaseBridge.java file like limbo56 said, and link manually as mentioned in documention https://watermelondb.dev/docs/Installation
> 
> it will work with new arch enabled.. i made these changes and it works
> 
> within MainApplication.kt file, import com.nozbe.watermelondb.WatermelonDBPackage
> 
> later add it within getPackages function packages.add(WatermelonDBPackage())

how do we check if JSI is really running?

**Comment by saurabhsaneja** [comment]
@rohankm @Durwen21 those steps are not for expo, they were for react Native cli.. i could make it work by disabling jsi. Just follow manual linking steps as mentioned in the link i shared above

**Comment by rohankm** [comment]
> I don't think so.. for jsi it will be
> 
> `packages.add(WatermelonDBJSIPackage())`
> 
> You can easily check the difference between manual installation and JSI installation by checking the link below https://watermelondb.dev/docs/Installation

im sorry for the confusion.. its JSI package im using with expo 52

```            
import com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage
packages.add(WatermelonDBJSIPackage())```

**Comment by LovesWorking** [comment]
> > I don't think so.. for jsi it will be
> > `packages.add(WatermelonDBJSIPackage())`
> > You can easily check the difference between manual installation and JSI installation by checking the link below https://watermelondb.dev/docs/Installation
> 
> im sorry for the confusion.. its JSI package im using with expo 52
> 
> ```
> import com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage
> packages.add(WatermelonDBJSIPackage())```
> ```

Could you please offer some advice and code examples how you were able to get expo 52 working on Android? This would be super helpfu!

**Comment by saurabhsaneja** [comment]
@LovesWorking I cannot answer that because I have not worked with expo

**Comment by masoud-msk** [comment]
> Could you please offer some advice and code examples how you were able to get expo 52 working on Android? This would be super helpfu!

@LovesWorking To use the WatermelonDB in expo@0.52 project without enabling JSI:
1. Prebuild the expo project `npx expo prebuild`
1. Follow the _Linking Manually_ section of [the docs](https://watermelondb.dev/docs/Installation#android-react-native)
1. Run or build the project normally (e.g. `expo run:android`)

If this didn't work, enable `EXPO_USE_COMMUNITY_AUTOLINKING=1` env variable.

**Comment by LovesWorking** [comment]
> > Could you please offer some advice and code examples how you were able to get expo 52 working on Android? This would be super helpfu!
> 
> @LovesWorking To use the WatermelonDB in expo@0.52 project without enabling JSI:
> 1. Prebuild the expo project `npx expo prebuild`
> 1. Follow the _Linking Manually_ section of [the docs](https://watermelondb.dev/docs/Installation#android-react-native)
> 1. Run or build the project normally (e.g. `expo run:android`)
> 
> If this didn't work, enable `EXPO_USE_COMMUNITY_AUTOLINKING=1` env variable.
> 
> 

Thank you!

**Comment by rahulgwebdev** [comment]
> [@CodeWithBlaze](https://github.com/CodeWithBlaze) [@saurabhspinny](https://github.com/saurabhspinny)
> 
> ### Fix for Bridgeless Architecture Error on App Reload
> If you're running into the following error with the new architecture when reloading your app:
> 
> ```
> Caused by: java.lang.NullPointerException 
>   at com.facebook.react.runtime.BridgelessCatalystInstance.getReactQueueConfiguration(BridgelessCatalystInstance.kt:116)
>   at com.nozbe.watermelondb.WMDatabaseBridge.invalidate(WMDatabaseBridge.java:251) 
>   at com.facebook.react.internal.turbomodule.core.TurboModuleManager.invalidate(TurboModuleManager.java:417)
> ```
> 
> This issue arises because the new **Bridgeless architecture** does not support `CatalystInstance`, as mentioned in the [React Native source code](https://github.com/facebook/react-native/blob/980458c061580bbc004bf1ddc17f567fc51aaab8/packages/react-native/ReactAndroid/src/main/java/com/facebook/react/runtime/BridgelessReactContext.java#L86-L89).
> 
> ### Solution
> The fix involves replacing `getCatalystInstance().getReactQueueConfiguration().getJSQueueThread().runOnQueue()` with `runOnJSQueueThread()` to maintain compatibility with the Bridgeless architecture:
> 
> diff --git a/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java b/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
> index 117b2bc1f75217c685bc9cfa76b4e55b22e015dc..a678d5d1715d633c4518a04b11fd1198c53157e9 100644
> --- a/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
> +++ b/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java
> @@ -248,7 +248,7 @@ public class WMDatabaseBridge extends ReactContextBaseJavaModule {
>      public void invalidate() {
>          // NOTE: See Database::install() for explanation
>          super.invalidate();
> -        reactContext.getCatalystInstance().getReactQueueConfiguration().getJSQueueThread().runOnQueue(() -> {
> +        reactContext.runOnJSQueueThread(() -> {
>              try {
>                  Class<?> clazz = Class.forName("com.nozbe.watermelondb.jsi.WatermelonJSI");
>                  Method method = clazz.getDeclaredMethod("onCatalystInstanceDestroy");
> I’ve submitted [a pull request with this fix](https://github.com/Nozbe/WatermelonDB/pull/1875) and would appreciate it being merged. Hope this helps!

Thank you very much for the solution. I’m currently using version 0.27.1, and the issue still persists.
For anyone still encountering this problem, I’ve added a post-install hook to patch the affected file. Hopefully, this helps someone:

```
# scripts/patch-watermelondb.js
const fs = require("fs")
const path = require("path")

const filePath = path.join(
  process.cwd(),
  "node_modules/@nozbe/watermelondb/native/android/src/main/java/com/nozbe/watermelondb/WMDatabaseBridge.java"
)

try {
  if (fs.existsSync(filePath)) {
    // Read the file
    let content = fs.readFileSync(filePath, "utf8")

    // Replace the target line
    const newContent = content.replace(
      "reactContext.getCatalystInstance().getReactQueueConfiguration().getJSQueueThread().runOnQueue(() -> {",
      "reactContext.getJSMessageQueueThread().runOnQueue(() -> {"
    )

    // Only write if there was a change
    if (newContent !== content) {
      fs.writeFileSync(filePath, newContent, "utf8")
      console.log("Successfully patched WMDatabaseBridge.java")
    } else {
      console.log("No changes needed in WMDatabaseBridge.java")
    }
  } else {
    console.warn("WMDatabaseBridge.java not found at:", filePath)
  }
} catch (error) {
  console.error("Error patching WMDatabaseBridge.java:", error)
  process.exit(1)
}
```
And in package.json:

```
  "scripts": {
    "start": "expo start",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint",
    "postinstall": "node scripts/patch-watermelondb.js"
  },
```

**Comment by LovesWorking** [comment]
I also updated this expo plugin to work with EXPO SDK 52 and 53 if anyone is having issues! 

https://github.com/LovesWorking/watermelondb-expo-plugin-sdk-52-plus

**Comment by ghost** [comment]
any news about this?, I'm using this great plugin because of its great sync capabilities without third part plugins, and now I required to migrate do react native 79 with new arch enabled cant use it anymore

**Comment by LovesWorking** [comment]
Use my expo plugin to make it work and you're good > any news about this?, I'm using this great plugin because of its great sync capabilities without third part plugins, and now I required to migrate do react native 79 with new arch enabled cant use it anymore

**Comment by 3210jr** [comment]
> Use my expo plugin to make it work and you're good > any news about this?, I'm using this great plugin because of its great sync capabilities without third part plugins, and now I required to migrate do react native 79 with new arch enabled cant use it anymore 
> 
> 

I use this one in prod for 3 apps and it's working really really well.

**Comment by marcibk** [comment]
I assume WatermelonDB is not actively maintained anymore, which sucks :(. Has anyone figured out on how to run WatermelonDB with rn 0.81+ & new architecture? Guess this is not rly possible atm?

**Comment by Dallas62** [comment]
I see a lot of activity on this thread.

I’m running with the new Architecture without any issue.
Can you precise your issues ? Specific to 0.81 ?

**Comment by LovesWorking** [comment]
> I assume WatermelonDB is not actively maintained anymore, which sucks :(. Has anyone figured out on how to run WatermelonDB with rn 0.81+ & new architecture? Guess this is not rly possible atm?

It's maintained..

**Comment by ghost** [comment]
I make it run with new arch, using the latest version but is still in beta, maybe can set it as release on npm?
react native 0.79.7
watermelon 0.28.1-0

**Comment by fillipeags** [comment]
how did you managed to make it work @juanpvmsnz  ? I'm planning on turning on new arch and on my latest tests i was having some trouble turning on watermelon to work on it

**Comment by DevYuns** [comment]
WatermelonDB 0.28.0 is working smoothly with react-native@0.81.5 and expo@54.0.23(newArch=true) on my end.

**Comment by brianalexander** [comment]
@DevYuns Can you share what you did?  I've tried "plugin-less" and using `"@morrowdigital/watermelondb-expo-plugin": "2.4.0-beta.0"`, but nothing is working for me.  Also on react-native@0.81.5 and expo@54.0.23(newArch=true).

I get one of two errors

```
 ERROR  [TypeError: Cannot read property 'initializeJSI' of null] 

Code: index.ts
   6 |
   7 | // Create the adapter
>  8 | const adapter = new SQLiteAdapter({
     |                                  ^
   9 |   schema: mySchema,
  10 |   jsi: true,
  11 |   onSetUpError: (error) => {
Call Stack
  <global> (src/db/index.ts:8:34)
  <global> (src/app/(home)/_layout.tsx:9)
```

OR

```
 ERROR  [Diagnostic error: NativeModules.WMDatabaseBridge is not defined! This means that you haven't properly linked WatermelonDB native module. Refer to docs for instructions about installation (and the changelog if this happened after an upgrade).] 

Code: index.ts
   6 |
   7 | // Create the adapter
>  8 | const adapter = new SQLiteAdapter({
     |                                  ^
   9 |   schema: mySchema,
  10 |   jsi: true,
  11 |   onSetUpError: (error) => {
Call Stack
  <global> (src/db/index.ts:8:34)
```

This is on an Android emulator.

No idea what I'm missing.

```
npx expo prebuild --clean
npx expo run:android --no-build-cache
```

**Comment by DevYuns** [comment]
@brianalexander add this code into `proguard-rules.pro`.

```
# WatermelonDB
-keep class com.nozbe.watermelondb.** { *; }
```

Otherwise check this code.
```
// MainApplication.kt

...
import com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage
...

class MainApplication : Application(), ReactApplication {
  override val reactNativeHost: ReactNativeHost = ReactNativeHostWrapper(
      this,
      object : DefaultReactNativeHost(this) {
        override fun getPackages(): List<ReactPackage> =
            PackageList(this).packages.apply {
              // Packages that cannot be autolinked yet can be added manually here, for example:
              // add(MyReactNativePackage())
              add(WatermelonDBJSIPackage())   <---------- here
            }
      }
  )
```

**Comment by vinayak-nangnurkar** [comment]
> WatermelonDB 0.28.0 is working smoothly with react-native@0.81.5 and expo@54.0.23(newArch=true) on my end.
Hi @DevYuns  👋

I’m currently trying to use **WatermelonDB 0.28.0** with React Native and facing multiple build issues related to Gradle (task dependency errors like `generateDebugResValues`, `extractDeepLinksDebug`, etc.).

I noticed you mentioned that it’s working smoothly for you with **React Native 0.81.5**, so I wanted to understand your setup.

Could you please share the following details?

* React Native version
* Gradle version (from `gradle-wrapper.properties`)
* Android Gradle Plugin version
* Kotlin version
* Whether you applied any patches or custom fixes (e.g., task dependencies, disabling validation, etc.)

I’m currently using:

* React Native: 0.82.1
* Gradle: 8.14
* Kotlin: 1.9.24

and facing compatibility issues with WatermelonDB.

It would be really helpful to know your exact configuration so I can align accordingly.

Thanks in advance! 🙏

**Comment by DevYuns** [comment]
@vinayak-nangnurkar Here it is.


  - React Native: `0.83.2`
  - Gradle wrapper: `8.14.3`
    - from `android/gradle/wrapper/gradle-wrapper.properties`
  - Android Gradle Plugin: `8.12.0`
    - this one is inherited via the installed React Native Gradle plugin / version catalog, not hardcoded directly in my app `build.gradle`
  - Kotlin: `2.1.20`

  WatermelonDB version:
  - `@nozbe/watermelondb`: `^0.28.0`

  WatermelonDB Android setup:
  - I’m using the JSI module and included it in `android/settings.gradle` like this:
    - `include ':watermelondb-jsi'`
    - project dir -> `../node_modules/@nozbe/watermelondb/native/android-jsi`
  - And in `android/app/build.gradle`:
    - `implementation project(':watermelondb-jsi')`

**Comment by vinayak-nangnurkar** [comment]
Thanks❤️ @DevYuns  — really appreciate your help on this. It means a lot! 🙌

**Comment by DevYuns** [comment]
No worries 😄
