### ISSUE TITLE
TypeError: from.from is not a function. (In 'from.from(observables[0])', 'from.from' is undefined)

### ISSUE THREAD

**Issue by YajanaRao** [Nozbe/WatermelonDB#502]
Here is my component 

```
const PlaylistItem = ({playlist}) => {
  console.log(playlist);
    return (
    <List.Item
      title={playlist.title}
      description="by you"
      left={props => <List.Icon {...props} icon="audiotrack" />}
    />
  );
};

const enhance = withObservables(['playlist'], ({playlist}) => ({
  playlist
}));

export default enhance(PlaylistItem);
```

Here is how I call the component
```
<FlatList
          data={this.state.playlists}
          renderItem={(item) => <PlaylistItem playlist={item} />}
        />
```

This is my query

```
async componentDidMount(){
    const playlists = database.collections.get('playlists');
    const allPlaylists = await playlists.query().fetch();
    console.log("playlist ", allPlaylists);
    this.setState({
      playlists: allPlaylists
    })
  }
```

Please help me. I am not able to understand the problem. 
If I remove withObservables and export as it is, it is working fine.

**Comment by YajanaRao** [comment]
The walk around for this issue is to change 
`var from = require('rxjs/observable/from');`
to
`var from = require('rxjs');`
in  `\node_modules\@nozbe\with-observables\dist\with-observables.cjs.js`

**Comment by pranavbabu** [comment]
@YajanaRao  Why did you close the issue?

**Comment by YajanaRao** [comment]
If you have similar issue I will reopen it.

**Comment by pranavbabu** [comment]
I do

**Comment by pranavbabu** [comment]
Guys, I got also error `ExceptionsManager.js:44 TypeError: (0 , _defer.defer) is not a function`
After using `observe()` on collection while switching to `fetch()` method works, but I guess it will not handle changes. Something with library imports...
![image](https://user-images.githubusercontent.com/54139019/66269543-47bc5d00-e852-11e9-961f-c15cbe35fbcd.png)

**Comment by pranavbabu** [comment]
Seems like with 0.15.0 the problem is solved.

**Comment by joshfarrant** [comment]
Sorry to reopen this discussion, but I was experiencing the same `from.from is undefined` that @YajanaRao was experiencing.

The solution they proposed (modifying the import in `with-observables.cjs.js` did resolve the issue, but obviously that's just a workaround, not a permanent fix.

Are there any suggestions as to what the underlying issue could be, and how that can be resolved? Is it as simple as changing the import, or coudl that have knock-on effects?

**Comment by auliakbarh** [comment]
I have same issue, anyone can fix it?

**Comment by imsheth** [comment]
still facing the issue with 

> "@nozbe/watermelondb": "^0.16.0",
    "@nozbe/with-observables": "^1.0.5",

**Comment by gliesche** [comment]
Also facing this issue with:

```
"@nozbe/watermelondb": "0.17.1",
"@nozbe/with-observables": "1.0.5",
```

**Comment by tobiasorth** [comment]
Same here, still investigating:
```
"@nozbe/watermelondb": "0.19.0",
"@nozbe/with-observables": "1.0.5"
```

**Comment by Batuu13** [comment]
I am also experiencing this issue! Also, lack of examples for separated DB calls is a pain in the ass! I am trying to write a service to separate DB calls and components but there is no tutorial :/

**Comment by StebanDev** [comment]
@radex i think this is something that should be fixed right? I am having the same issue with latest version and @YajanaRao 's solution did the trick but I'm not sure if that could bring another issues.

**Comment by radex** [comment]
@StebanDev I think next version of WatermelonDB ought to fix the issue

**Comment by WrathChaos** [comment]
@YajanaRao's solution is working but this is really not a good solution.

**Comment by Cully-Curwen** [comment]
Also running into this problem with; 
```
    "react-native": "0.63.3",
    "@nozbe/watermelondb": "^0.20.0",
    "@nozbe/with-observables": "^1.0.7",
```

using Hermes engine on Android,

**Comment by igorcaldeira** [comment]
Same issue here, any permanent solution ?

**Comment by markwillis82** [comment]
I'm getting this still on
`    "@nozbe/watermelondb": "^0.20.0",
    "@nozbe/with-observables": "^1.0.8",
    "@react-native-community/async-storage": "^1.12.1",
    "@react-native-community/masked-view": "^0.1.10",
    "@react-navigation/bottom-tabs": "^5.11.3",
    "@react-navigation/native": "^5.9.0",
    "@react-navigation/stack": "^5.13.0",
    "@reduxjs/toolkit": "^1.5.0",
    "react": "16.13.1",
    "react-native": "0.63.4",
`

I've removed Flipper and now I also get an error of " ld: library not found for -lDoubleConversion clang: error: linker command failed with exit code 1 (use -v to see invocation)" .

**Comment by markwillis82** [comment]
I've managed to get this to work by changing the import:

```
// var from = require('rxjs/observable/from');
import { from as rxFrom } from 'rxjs';
const from = {from: rxFrom}; // just used for keeping the function calls working as expected
```
